{% set version = "1.1.0" %}

package:
  name: asphalt-web
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/asphalt-web/asphalt-web-{{ version }}.tar.gz
  sha256: 17039c9673ed3491f3276fc737480b772f63280c885201e33c69a93d7c37d84c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - asphalt >=4.8,<5

test:
  imports:
    - asphalt.web

about:
  home: https://github.com/asphalt-framework/asphalt-web
  doc_url: ihttps://asphalt-web.readthedocs.org
  dev_url: https://github.com/asphalt-framework/asphalt-web
  license: Apache-2.0
  license_file: LICENSE
  summary: Web framework integrations for the Asphalt framework

extra:
  recipe-maintainers:
    - davidbrochart
