{% set version = "1.3.1" %}

package:
  name: asphalt-web
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/asphalt-web/asphalt-web-{{ version }}.tar.gz
  sha256: afd05a8ad1bcf511b91396b74d84e72b6b7cf446faefa4b21c31ebe6d0312352

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.8
    - asphalt >=4.8,<5

test:
  imports:
    - asphalt.web

about:
  home: https://github.com/asphalt-framework/asphalt-web
  doc_url: https://asphalt-web.readthedocs.org
  dev_url: https://github.com/asphalt-framework/asphalt-web
  license: Apache-2.0
  license_file: LICENSE
  summary: Web framework integrations for the Asphalt framework

extra:
  recipe-maintainers:
    - davidbrochart
