{% set version = "1.3.0" %}

package:
  name: asphalt-web
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/asphalt-web/asphalt-web-{{ version }}.tar.gz
  sha256: c94fa992d6eebe0a49eeedd2080b9826de0af5c36e810ca450cb01ecb20cd3dc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.8
    - asphalt >=4.8,<5

test:
  imports:
    - asphalt.web

about:
  home: https://github.com/asphalt-framework/asphalt-web
  doc_url: https://asphalt-web.readthedocs.org
  dev_url: https://github.com/asphalt-framework/asphalt-web
  license: Apache-2.0
  license_file: LICENSE
  summary: Web framework integrations for the Asphalt framework

extra:
  recipe-maintainers:
    - davidbrochart
